workflows:
  my-build-workflow:
    name: Build APK and AAB
    instance_type: linux
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk
