import { Shop, MenuItem, PromoCode } from './types';

export const SHOPS: Shop[] = [
  // --- RESTAURANTS (EGYPT) ---
  {
    id: 'rest-1',
    name: 'كشري أبو طارق',
    category: 'restaurants',
    image: 'https://images.unsplash.com/photo-1561651823-34fed022540e?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    reviewsCount: 4210,
    deliveryTime: 20,
    deliveryFee: 15,
    minOrder: 40,
    distance: 1.2,
    tags: ['كشري', 'شعبي', 'مصري', 'توصيل سريع'],
    featured: true,
  },
  {
    id: 'rest-2',
    name: 'بافلو برجر - Buffalo Burger',
    category: 'restaurants',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    reviewsCount: 1890,
    deliveryTime: 35,
    deliveryFee: 25,
    minOrder: 80,
    distance: 3.1,
    tags: ['برجر', 'أمريكي', 'بطاطس', 'وجبات سريعة'],
    featured: true,
  },
  {
    id: 'rest-3',
    name: 'كبابجي صبحي كابر',
    category: 'restaurants',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 5120,
    deliveryTime: 45,
    deliveryFee: 35,
    minOrder: 120,
    distance: 4.8,
    tags: ['مشويات', 'كباب وكفتة', 'طواجن', 'أكل مصري'],
    featured: true,
  },
  {
    id: 'rest-4',
    name: 'بيتزا بريمو - Primo Pizza',
    category: 'restaurants',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    rating: 4.4,
    reviewsCount: 840,
    deliveryTime: 30,
    deliveryFee: 18,
    minOrder: 60,
    distance: 2.2,
    tags: ['بيتزا', 'إيطالي', 'فطير شرقي', 'معجنات'],
    featured: false,
  },
  {
    id: 'rest-5',
    name: 'شاورما كرم الشام',
    category: 'restaurants',
    image: 'https://images.unsplash.com/photo-1644704170910-a0cdf183649b?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    reviewsCount: 3120,
    deliveryTime: 25,
    deliveryFee: 15,
    minOrder: 50,
    distance: 1.5,
    tags: ['شاورما', 'سوري', 'فتة شاورما', 'عربي'],
    featured: false,
  },

  // --- GROCERY (EGYPT) ---
  {
    id: 'groc-1',
    name: 'سوبرماركت سعودي - Seoudi',
    category: 'grocery',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 6200,
    deliveryTime: 40,
    deliveryFee: 20,
    minOrder: 100,
    distance: 2.5,
    tags: ['سوبرماركت', 'أغذية طازجة', 'منتجات ألبان', 'مستلزمات منزلية'],
    featured: true,
  },
  {
    id: 'groc-2',
    name: 'مخبز وحلواني العبد',
    category: 'grocery',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    reviewsCount: 4800,
    deliveryTime: 25,
    deliveryFee: 15,
    minOrder: 50,
    distance: 1.8,
    tags: ['مخبوزات', 'حلويات شرقية', 'كيك', 'حلاوة المولد'],
    featured: true,
  },
  {
    id: 'groc-3',
    name: 'سوق الخضار والفاكهة الطازجة',
    category: 'grocery',
    image: 'https://images.unsplash.com/photo-1610832958506-ee5633619141?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    reviewsCount: 630,
    deliveryTime: 30,
    deliveryFee: 12,
    minOrder: 30,
    distance: 1.1,
    tags: ['خضار طازج', 'فاكهة موسمية', 'خضراوات مجهزة', 'صحي'],
    featured: false,
  },

  // --- CAFES (EGYPT) ---
  {
    id: 'cafe-1',
    name: 'سيلانترو كافيه - Cilantro',
    category: 'cafes',
    image: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    reviewsCount: 1540,
    deliveryTime: 25,
    deliveryFee: 20,
    minOrder: 50,
    distance: 1.3,
    tags: ['قهوة مختصة', 'مشروبات باردة', 'سندوتشات فطور', 'حلويات'],
    featured: true,
  },
  {
    id: 'cafe-2',
    name: 'تي بي إس - TBS (The Bakery Shop)',
    category: 'cafes',
    image: 'https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 2200,
    deliveryTime: 20,
    deliveryFee: 18,
    minOrder: 60,
    distance: 2.1,
    tags: ['كرواسون', 'دونات', 'مخبوزات طازجة', 'قهوة صباحية'],
    featured: true,
  }
];

export const MENU_ITEMS: MenuItem[] = [
  // --- KOSHARY ABOU TAREK ITEMS ---
  {
    id: 'item-kat-1',
    shopId: 'rest-1',
    name: 'علبة كشري أبو طارق سوبر جامبو',
    description: 'الأرز المصري الأصيل، المكرونة المتنوعة، العدس بجبة، الحمص، مغطاة بالبصل المقرمش والصلصة المميزة والدقة والصلصة الحارة.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1561651823-34fed022540e?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    tags: ['الأكثر مبيعاً', 'شعبي مصري'],
    popular: true,
  },
  {
    id: 'item-kat-2',
    shopId: 'rest-1',
    name: 'علبة كشري وسط',
    description: 'علبة كشري حجم متوسط مع أكياس الدقة والصلصة المخصوصة والصلصة الحارة.',
    price: 30,
    image: 'https://images.unsplash.com/photo-1561651823-34fed022540e?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    tags: ['كشري'],
    popular: true,
  },
  {
    id: 'item-kat-3',
    shopId: 'rest-1',
    name: 'طاجن مكرونة باللحمة المفرومة',
    description: 'طاجن مكرونة فرن مطهوة بصلصة الطماطم الغنية واللحم المفروم المتبل المطهو بعناية.',
    price: 55,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    tags: ['طواجن'],
  },
  {
    id: 'item-kat-4',
    shopId: 'rest-1',
    name: 'أرز باللبن في الفرن مكسرات',
    description: 'أرز باللبن كريمي غني، محمر في الفرن ومزين بالفستق وجوز الهند والزبيب.',
    price: 25,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    tags: ['حلويات'],
  },

  // --- BUFFALO BURGER ITEMS ---
  {
    id: 'item-bb-1',
    shopId: 'rest-2',
    name: 'دبل باستر برجر وجبة',
    description: 'قطعتين لحم مشوي بوزن 150 جرام لكل قطعة، جبنة شيدر سائحة، خس، خيار مخلل، صوص باستر السري. تقدم مع بطاطس وكان بيبسي.',
    price: 165,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    tags: ['برجر لحم', 'الأكثر مبيعاً'],
    popular: true,
  },
  {
    id: 'item-bb-2',
    shopId: 'rest-2',
    name: 'كريسبي تشيكن ساندرز وجبة',
    description: 'صدر دجاج مقرمش ومتبل، مغطى بجبنة شيدر، صوص رانش كريمي، خس طازج. تقدم مع بطاطس ومشروب.',
    price: 145,
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    tags: ['برجر دجاج', 'مقرمش'],
    popular: true,
  },
  {
    id: 'item-bb-3',
    shopId: 'rest-2',
    name: 'بطاطس مقلية مع صوص الجبن والهلابينو',
    description: 'بطاطس سميكة ومقرمشة مغطاة بصوص جبنة شيدر غنية وقطع الهلابينو المخلل الحار.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=400&q=80',
    rating: 4.6,
  },

  // --- SOBHY KABER ITEMS ---
  {
    id: 'item-sk-1',
    shopId: 'rest-3',
    name: 'نصف كيلو مشكل كباب وكفتة',
    description: 'كباب وكفتة بتلو بلدي طازج، مشوي على الفحم الطبيعي، يقدم مع خبز بلدي ساخن، سلطة خضراء وطحينة.',
    price: 240,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    tags: ['مشويات بلدي', 'عائلي'],
    popular: true,
  },
  {
    id: 'item-sk-2',
    shopId: 'rest-3',
    name: 'طاجن ورق عنب بالكوارع الشهير',
    description: 'ورق عنب محشي بلدي مطبوخ في طاجن فخار بالفرن مع قطع كوارع بلدي مخلية طرية ولذيذة جداً.',
    price: 135,
    image: 'https://images.unsplash.com/photo-1633383718081-22ac93e3dbf1?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    tags: ['طواجن', 'أكثر طلباً'],
    popular: true,
  },
  {
    id: 'item-sk-3',
    shopId: 'rest-3',
    name: 'ملوخية صبحي كابر بالطشة الشهيرة',
    description: 'شوربة ملوخية خضراء طازجة مخفوقة ومجهزة على أصولها، تقدم مع الطشة الرهيبة المخصوصة بالثوم والكزبرة.',
    price: 55,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    tags: ['مقبلات وشوربة'],
  },

  // --- PRIMO PIZZA ITEMS ---
  {
    id: 'item-pp-1',
    shopId: 'rest-4',
    name: 'بيتزا مارغريتا إيطالياني',
    description: 'صلصة طماطم متبلة بالزعتر البري، جبنة موزاريلا طبيعية غنية، ريحان طازج، وزيت زيتون بكر ممتاز.',
    price: 85,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=400&q=80',
    rating: 4.5,
    tags: ['بيتزا', 'نباتي'],
    popular: true,
  },
  {
    id: 'item-pp-2',
    shopId: 'rest-4',
    name: 'فطير مشلتت شرقي بالسجق والجبن',
    description: 'فطير شرقي مورق بالسمن البلدي، محشي سجق بلدي شرقي، فلفل رومي، طماطم، زيتون أسود، وجبنة رومي وموزاريلا ذائبة.',
    price: 110,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    tags: ['فطير شرقي', 'مميز'],
    popular: true,
  },

  // --- KARAM EL SHAM ITEMS ---
  {
    id: 'item-kes-1',
    shopId: 'rest-5',
    name: 'ماريا شاورما دجاج سوري دبل',
    description: 'خبز صاج سوري محشو بشاورما دجاج، تومية، خيار مخلل، وجبنة موتزاريلا، مشوية على الجريل بصوص التتبيلة السحرية.',
    price: 75,
    image: 'https://images.unsplash.com/photo-1561651823-34fed022540e?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    tags: ['شاورما', 'دجاج'],
    popular: true,
  },
  {
    id: 'item-kes-2',
    shopId: 'rest-5',
    name: 'فتة شاورما لحم كرم الشام',
    description: 'طبق أرز بسمتي ذهبي مبهر مغطى بشرائح شاورما لحم بلدي، مكعبات خبز شامي مقلي، ثومية مخصوصة ومكسرات.',
    price: 115,
    image: 'https://images.unsplash.com/photo-1644704170910-a0cdf183649b?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    tags: ['فتة', 'لحم'],
    popular: true,
  },

  // --- SEOUDI SUPERMARKET ITEMS ---
  {
    id: 'item-sm-1',
    shopId: 'groc-1',
    name: 'طبق بيض أبيض طازج - 30 بيضة',
    description: 'بيض مزارع أبيض طازج غني بالبروتين، من مزارع سعودي المعتمدة.',
    price: 145,
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    popular: true,
  },
  {
    id: 'item-sm-2',
    shopId: 'groc-1',
    name: 'حليب كامل الدسم جهينة 1 لتر - عبوة 4 حبات',
    description: 'حليب معقم طويل الأجل، خالي من المواد الحافظة، الاختيار الأول للأسرة المصرية.',
    price: 148,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    popular: true,
  },
  {
    id: 'item-sm-3',
    shopId: 'groc-1',
    name: 'جبنة فيتا دومتي 500 جرام',
    description: 'جبنة فيتا نباتي الدهن طعم طبيعي غني، ناعمة وسهلة الفرد.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
  },
  {
    id: 'item-sm-4',
    shopId: 'groc-1',
    name: 'أرز مصري الساعة فاخر 5 كجم',
    description: 'أرز مصري حبة عريضة منتقاة بعناية، مغسول وصالح للطبخ فوراً، جودة ممتازة.',
    price: 175,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
  },

  // --- EL ABD BAKERY ITEMS ---
  {
    id: 'item-ea-1',
    shopId: 'groc-2',
    name: 'علبة بسبوسة سادة فاخرة بالبلدي',
    description: 'بسبوسة مصرية أصلية مخبوزة بالسمن البلدي الطبيعي وشربات السكر الخفيف، ناعمة وذائبة.',
    price: 85,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    tags: ['شرقي', 'الأكثر مبيعاً'],
    popular: true,
  },
  {
    id: 'item-ea-2',
    shopId: 'groc-2',
    name: 'كرواسون شوكولاتة العبد - كيس 5 قطع',
    description: 'كرواسون هش ومحشو بشوكولاتة العبد الغنية، طازج ومثالي للافطار الخفيف.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
  },

  // --- CILANTRO COFFEE ITEMS ---
  {
    id: 'item-cc-1',
    shopId: 'cafe-1',
    name: 'أيس كراميل ماكياتو كبير',
    description: 'شوت مزدوج إسبريسو Cilantro مع حليب كامل الدسم، صوص كراميل كلاسيكي وقطع ثلج منعشة.',
    price: 75,
    image: 'https://images.unsplash.com/photo-1595434061149-8657e0a9ddf8?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    tags: ['بارد', 'أكثر طلباً'],
    popular: true,
  },
  {
    id: 'item-cc-2',
    shopId: 'cafe-1',
    name: 'فلات وايت ساخن كلاسيكي',
    description: 'إسبريسو غني ممزوج ببراعة مع حليب مبخر ناعم طبقة حريرية لتستمتع بمذاق رائع.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    tags: ['ساخن', 'قهوة'],
    popular: true,
  },

  // --- TBS ITEMS ---
  {
    id: 'item-tbs-1',
    shopId: 'cafe-2',
    name: 'نصف درزن دوناتس مشكلة - TBS',
    description: 'علبة توفير تحتوي على 6 قطع دونات طازجة ومزينة بالنكهات المتنوعة (نوتيلا، لوتس، سكر وبودرة وبستاشيو).',
    price: 180,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    tags: ['حلويات غربية', 'كرواسون ودوناتس'],
    popular: true,
  },
  {
    id: 'item-tbs-2',
    shopId: 'cafe-2',
    name: 'كرواسون زبدة فرنسي سادة فاخر',
    description: 'كرواسون TBS الهش والمقرمش المخبوز بالزبدة الفرنسية المستوردة مائة بالمائة طازج كل ساعة.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    tags: ['كرواسون'],
    popular: true,
  }
];

export const PROMO_CODES: PromoCode[] = [
  {
    code: 'MASR30',
    discountPercent: 30,
    minSubtotal: 100,
    description: 'خصم 30% للطلبات فوق 100 جنيه مصري',
  },
  {
    code: 'FREE',
    discountFixed: 20,
    minSubtotal: 150,
    description: 'خصم 20 جنيه مصري من قيمة التوصيل للطلبات فوق 150 جنيه',
  },
  {
    code: 'EGYPT10',
    discountPercent: 10,
    minSubtotal: 50,
    description: 'خصم 10% على كافة طلباتك ومطاعمك المفضلة بجمهورية مصر العربية',
  }
];
